### ISSUE TITLE
Munkautasítás: bejelentések sorrendje a listán

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#1]
A munkautasítás nyomtatása során a sorrend: kerület neve ->közterület neve.
A szerelők adott kerületet egyszerre járnak le ezért nem jó, ha vissza kell menni egy már járt területre, mert az a listán máshol jelent meg

**Comment by suddenslap** [comment]
Cím szerint rendezve a munkautasítás PDF-en található címek listája.
