### ISSUE TITLE
MIRTUSZ export: filenév

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#10]
A MIRTUSZ felé küldendő filenévnek minden esetben a "BDK_EXPORT_" előtaggal kell kezdődnie.

**Comment by KoToITKft** [comment]
a export végén le kell tenni még egy export.txt állományt is, hogy a MIRTUSZ azonnal elkezdje a feldolgozást. A feldolgozás végén a MIRTUSZ törli az export.txt állományt

**Comment by KoToITKft** [comment]
FONTOS! Az file előtag "BDK_EXPORT_" csupa nagybetű, a expot jelző file neve pontosan "Export_Ready.txt" ez utóbbi lehet üres, csak a filenév számít.

**Comment by suddenslap** [comment]
javítva 1.0.0.3
