### ISSUE TITLE
Oszlop sorrend hiba

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#12]
"Az új KVILban fejléc oszlopsorrend nem működik több oszlopban sem. (időpont, kerület) össze vissza van ha a fejlécre kattintasz, valamint az ellenkező irányba nem fordítja át ugyan úgy marad ha többször kattintasz azonos fejlécre."

Ez egy idézet. Lehet, hogy nem is hiba a hiba, csak nem tudják a sorrendek logikáját (összeadodnak-e a sorrendek vagy mindig új sorrend van,, ha új oszlopra kattints stb.)
Checkolni kellene.

**Comment by suddenslap** [comment]
Nem sikerült a jelzett problémát előidéznem, pedig a megnevezett oszlopokat is teszteltem. A rendezés úgy megy, hogy alapesetben egy természetes adatbázis sorrendet kapunk. Ha rákattintunk az oszlopra, megjelenik egy nyilacska, ami ha felfelé mutat, növekvő sorrendet kapunk, ha lefelé mutat csökkenő sorrendet kapunk. Ezek között a változtatás kattintással lehetséges, tehát első katt növekvő sorrend, második katt, csökkenő sorrend, harmadik katt nincs rendezés, és így tovább körbe-körbe.
