### ISSUE TITLE
log csökkentése

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#14]
A részletes log miatt (mennyisége és hossza miatt), az adatbázis mérete nagyon nagy lesz. Csökkenteni kell (ésszerű határon belül) a log méretét.

**Comment by KoToITKft** [comment]
Elvben ez a teszt környezetben okozott eddig gondot.
Ha van rá ötleted, akkor tegyünk érte.

**Comment by suddenslap** [comment]
Kikapcsolatam a részletes logolást. Kizárólag hiba esetén töltöm fel szöveggel a log bejegyzéseket, egyéb esetben úgyis elég az adott transzfer esemény státusza (tehát hogy sikeres volt-e vagy sem).
Ezt a Márkaműhelyes és Mirtuszos kapcsolatoknál egyaránt megcsináltam, ami jelentős adatmennyiség csökkenést jelent.
v1.0.0.6
