### ISSUE TITLE
BDK.HU api változott: fotó mező

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#15]
A https://app.swaggerhub.com/apis/BORN.hu/BDK_ticket_API/1.1.6-oas3#/partners/searchReportsJson
tanulsága szerint bekerült az XML szerkezetbe a fénykép. Ezt akkor lehet a bejelentés mellé mint csatolmányt tárolni.

**Comment by KoToITKft** [comment]
Ez most a legprioritásosabb megoldandó dolog.

**Comment by suddenslap** [comment]
Implementálva v1.0.0.4
