### ISSUE TITLE
Intéző: lapozó

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#16]
intézőn belül, ha pl. a bejelentéseknél ellapozunk az akárhányadik oldalra és átváltunk bal oldalon egy másik menüpontba,  ugyanazon az oldalon marad a lapozó, egyszerűbb lenne, ha ilyen váltásnál az új ablak (munkaszámok, szerelőcsapatok, stb.) visszatérne az első oldalra a lapozó
(vagyis ha a bejelentéseknél a 8 oldalon voltunk és átváltunk a munkautasításokra, akkor ott is a 8. oldalon kezdünk.)

**Comment by suddenslap** [comment]
Implementálva v1.0.0.4
