### ISSUE TITLE
N/A címek

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#24]
Ne jöjjön át NA-cím a rendszeren, se honlap, se MIRTUSZ esetén -> ha van kerület jelzés, vagy irányítószám akkor az adott kerülethez sorolja be a címeket, majd a többi adatot címkiegészítésként tegye be.

**Comment by KoToITKft** [comment]
Egyáltalán nem akarnak N/A címekkel foglalkozni. Azt kellene megnézni, hogyha nem tudunk egy címet belőni, akkor hogyan tudjuk az visszadobni a küldő rendszer felé és persze azt is, hogy az ilyen címek ne jelenjenek meg sehol (listában sem, számolásokban sem.)

**Comment by suddenslap** [comment]
A címadatbázis úgy épül fel, hogy utca->település->terület, tehát "Őrlő utca"->Budapest 03->Belváros
Ennek megfelelően ha nem tudunk lemenni utca szintig, akkor nem tudjuk bejelentéshez kapcsolni. Így volt a régi programban is, onnan lett átvéve, ennek a megmódosítása nagyon sok meló, mivel erre épül minden logika.

A fenti brutális módosítást elkerülve az alábbi eseteket látom a jegyben jelzett problémára:
- Kihasználják azt, hogy a területeket ki lehet osztani külön-külön felhasználóknak. Tehát ha valaki nem akar N/A-s címekkel foglalkozni, az kiveszi maga alól az N/A-s pipát és kész. Még mindig meg lehet tartani 1-2 embert, akik N/A-s területhez is vannak rendeve, s akik szúrópróbaszerűen ellenőrzik az N/A-s címeket és kézzel utánaállítják ha úgy ítélik meg.
- Megcsináljuk azt, hogy nem jön át N/A-s cím, soha sehonnan. Ez kényelmes megoldás, de mindenképpen adatvesztés a részükről.
- Megcsináljuk azt, hogy ha jön egy címadatbázisban nem található cím, azzal mi bővítjük a címadatbázist. A régi rendszer ezt csinálta, ezért volt tele a címadatbázisa mindenféle értelmetlen utcanevekkel, mint pl "?", meg ".", meg "abc", stb..

Ez a probléma valahogy mindig előjön. Látni kell azt, hogy itt két külső rendszer felöl is jönnek cím infók, puritán szöveg formájában. Elég egy elgépelt betű és a KVIL adatbázisában nem lesz egyezés. Tehát ha 100%-ban megbízunk a külső rendszerekben, akkor vegyük fel az általuk dobált címeket orrba-szájba a KVIL adatbázisába. Ha nem bízunk meg a külső rendszerekben, akkor hagyjuk meg az N/A területet, osszunk be alá 1-2 erős idegzetű embert, akik nézegetik a címeket.

Jelenleg egyik külső rendszer felé sem tudunk "visszadobni" hibás címre való hivatkozással bejelentést, tehát ez nem opció.

Természetesen a KVIL címkezelést is meg lehet reformálni, ahogy akarják, de azt biztos hogy csak díjazás ellenében fogom tudni bevállalni, mert az rohadt nagy meló lesz.

Szóval ezt én nem tudom eldönteni, akárhányszor is kérik hogy oldjuk meg a problémát. Nekem tökmindegy, hogy melyik utat választják a fenti 3 + 1 lehetségesből, nem én használom a rendszert.

**Comment by KoToITKft** [comment]
Jelenleg 2 user (Pintér Laci és Én) felügyeljük az N/A címeket.
Szerintem rábeszélem őket hogy ez maradjon is így.
