### ISSUE TITLE
Címkiegészítés mező

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#25]
Ha jó a cím ez ne legyen megismételve  a címkiegészítésbe, viszont az itt szereplő infók ne vesszenek el- ne legyenek felülírva  !

**Comment by KoToITKft** [comment]
Hm! Ha jól gondolom ebbe nincs beleszólásunk, az ebben a mezőben érkező adat a forrás rendszerből érkezik, mi csak mutogatjuk.

**Comment by suddenslap** [comment]
Itt szerintem megint van egy kis félreértés. A címkiegészítésben megjelenő cím, az nem az a cím, amit a bejelentéshez társítanak a KVIL-ben, hanem a forrásrendszerből átvett módosítatlan cím. Tehát ez még akkor is eltérhet, ha egyébként a rendszer talált címet a bejelentéshez mondjuk pl Nominatim-on keresztül. A "cím" szekció a címkiegészítésben nem jelenik meg amennyiben a cím parzolása rendben megtörtént, tehát csak akkor jelenik meg, ha a cím N/A lett. Ez a cím egyébként a forrásrendszerben szereplő pontos cím, tehát nem haszontalan, hogy ottvan.
Ez a mező írható, tehát felül lehet írni
v1.0.0.6

**Comment by suddenslap** [comment]
Javítva. Külön readonly mező "Forrásrendszer megjegyzés"-ben jön át az infó. A bejelentésben csak akkor jelenik meg ha van is benne valami, mert egyébként felesleges infó, meg ugye nem forrásrendszerből átvett esetben nem is releváns. Táblázatban is megjelenik oszlopként + a bejelentés/tervezett munka alapadatain is.
v1.0.0.6
