### ISSUE TITLE
bejelentés számlálás

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#27]
bejelentések ablaknál nem látszik, hogy az adott cím hány csapatnak/kinek van kiadva, erre kellene tudni szűrni és rendezni a fejlécben

**Comment by suddenslap** [comment]
Pontosan nem értem mi az a "bejelentés ablak". 
Ha az intéző Bejelentések táblázatáról van szó, akkor ott van egy "Kiosztva" oszlop, amiben látszanak a szerelőcsapatok.
Ha a munkautasítás entitás szerkesztőablakában található "Bejelentések" panel a szóban forgó "ablak", akkor ott nincs is értelme megjeleníteni, hiszen ugyanott megtekinthető a munkautasításhoz rendelt mindenki.

Zárom a bejelentést, mert szerintem erről sem fog kiderülni semmi. Ha van pontos kérés, kell nyitni egy új bejelentést.
