### ISSUE TITLE
BDK.API import

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#28]
Ezt látim a rendszerben:
![kép](https://user-images.githubusercontent.com/49682022/74294337-d465b300-4d3d-11ea-9771-57aedf5a7c90.png)
viszont a Postman szerint meg ez jön:
![kép](https://user-images.githubusercontent.com/49682022/74294362-e9424680-4d3d-11ea-990f-8ee4f9f6c8a2.png)
Valami elállt a programban?
Vagy a márkaműhely csinált (vissza) valamit?

**Comment by suddenslap** [comment]
Utca kereső logika javítva. Kiszedve az utca string szétválasztása, mostmár egy az egyben keresünk a kapott utcanévvel az adatbázisban. (v1.0.0.5)
