### ISSUE TITLE
Exportálás: fejlécek hiánya

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#31]
Exportált lekérdezésből hiányoznak a fejléc	 adatai, ezek jelenjenek meg (riport, terület, dátum, etc.)

**Comment by KoToITKft** [comment]
Itt nem tudom mire gondolt a költő. Ezt tisztázom.

**Comment by suddenslap** [comment]
Végignéztem az összes exportálási lehetőséget, és mindenhol volt fejléc. Zárom a bejelentést, ha valaki talál fejléc nélküli exportot, majd új bejelentés lesz.
