### ISSUE TITLE
Munkautasítás zárás után

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#32]
Ha a munkautasításon lezárunk egy címet és mentjük is a folyamatot, ne lehessen semmilyen módon módosítani, ha ez lehetséges kerüljön is ki a munkautasításból

**Comment by suddenslap** [comment]
Ezzel kapcs. annyit vettem észre, hogy ha egy munkautasítás címeit lezártuk, a munkautasítás popup "Alapadatok" lenyílója szerkeszthető maradt. De ha a munkautasítás újra a D&D területre húzzuk, akkor már read-only-ban jelenik meg ez is. Ezt javítottam, mást viszont nem találtam, mást nem lehetett szerkeszteni a munkautasításon, sem a lezárt bejelentéseken. v1.0.0.4
