### ISSUE TITLE
jelenléti ív fejléc

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#33]
A jelenléti ív fejlécén az az üzem jelenjen meg, ahová a névsor adott része tartozik

**Comment by suddenslap** [comment]
A jelenléti ív menüpont alatt található "Összesítő export"-ban ez már működik, minden egyes munkalap egy felhasználót jelent és a fejlécben az adott felhasználóhoz rendelt Terület jelenik meg, tehát gondolom a PDF exportra gondoltak. Tehát amikor kiválasztok egy felhasználót és egy hónapot, majd "Lekérdezés" és "Táblázat export" gombra kattintok. Az ekkor generálódó PDF fejlécébe betettem a felhasználó Területét, csakúgy mint az XLS exportban.

Ezt csak azért írtam le, mert a kérés megfogalmazása pongyola, tehát vagy az összes felhasználóról készítünk egy összesítő exportot, vagy 1db felhasználóról készítünk 1db havi jelenléti ívet. Tehát a "névsor adott része" megfogalmazás ebből a szempontból értelmetlen.
v1.0.0.4
