### ISSUE TITLE
FBI/Járókelő kiválasztás

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#34]
Új bejelentés FBI/Járókelő kiválasztásánál automatikusan ugorjon le az adott fülre és kérje az azonosítót

**Comment by KoToITKft** [comment]
Itt nem tudom mire gondolt a felvető. Elvben, hogy valami FBI/Járókelő legyen oda kell sétálni.

**Comment by suddenslap** [comment]
Értem a kérés motivációját. Ha FBI vagy Járókelő a bejelentő, akkor szükséges egy FBI vagy Járókelő azonosítót megadni. Viszont mind a két esetben van egy bepipálható flag, ami jelzi hogy a bejelentés FBI és/vagy Járókelő. Emiatt azt csináltam az eredeti kissé fura megoldási javaslat helyett, hogy ha kiválasztják az FBI-t bejelentőkét, akkor az FBI szekció flag-je bepipálódik, ugyanígy a járókelő flag-je is. Ezek egymást biztosan kizárják, tehát ha az FBI van bepipálva a Járókelő-ből kivesszük a pipát és fordítva. AZt viszont nem mertem megcsinálni, hogy ha nem ez a két érték van kiválasztva, hanem valaki beír valamit kézzel a bejelentő mezőbe, kivegye mindkét pipát, mert az lehet hogy üzletileg kellemetlen lenne. 
Nade a lényege az egésznek, hogyha ezek be vannak pipálva, és nincs megadva azonosító hozzájuk, akkor a rendszer amúgy is szól, tehát nem lehet azonosítók nélkül menteni és ez az üzleti elvárás itt.
v1.0.0.6
