### ISSUE TITLE
Melléklet jelzése

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#35]
Munkalapon jelölje, ha az adott címhez van melléklet csatolva, ha lehetséges ezt szeretnénk egy ikon formájában az intéző listájában is látni, amire ha rákattintunk, akkor az adott bejelentés „események” füléhez ugrik a program

**Comment by KoToITKft** [comment]
Szerintem ezt tudjuk. A 2(?) oszlop jelzi a mellékletet.

**Comment by suddenslap** [comment]
A kinyomtatott munkautasításon van melléklet oszlop (utolsó oszlop a bejelentések szekcióban), ahol ha van melléklet, megjelenik egy "igen". Az intéző bejelentések táblázatában is van csatolmányt jelző piktogram a 3. oszlopban. A rákattintós történetet nem tudom ezzel a táblázat komponenssel megoldani sajnos, ezt már anno is próbáltam. Ha a programból lesz webes vékony kliens, ott minden további nélkül megoldható...
Ennek megfelelően zárom a bejelentést. Ha mégsem erre gondoltak, akkor korrekt megfogalmazással majd új bejelentést kell felvenni.
