### ISSUE TITLE
munkalap: beosztott műszak

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#39]
munkalapon jelenjen meg a beosztott műszak (de, du, éj)

**Comment by KoToITKft** [comment]
Erre még rá fogok kérdezni

**Comment by suddenslap** [comment]
A "Beosztás" mezőbe raktam ezt az infót sortöréssel zárójelek közé és nem egy új oszlopba, mert az jelenlegi pdf koncepciót fixen kérték, azt nem akartam szétrombolni.
v1.0.0.6
