### ISSUE TITLE
Összeakadás

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#4]
USER1 felvett egy bejelentést
USER2 észrevette és munkautasításba húzta
USER1 fényképeket akart csatolni, miközben USER2 már behúzta a munkautasításba
USER2 nem tudta lementeni a munkautasítást, 
USER1 nem tudta szerkeszteni a bejelentést, merthogy piros lett, mivel munkautasításon volt.
A megoldás az volt, hogy USER1 létrehozott egy munkautasítást és abba húzta bele a bejelentést.
Ezt már tudta menteni.

**Comment by suddenslap** [comment]
Javítva.
1.0.0.6
