### ISSUE TITLE
munkautasítás: címkieg.

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#40]
munkalapon a címkiegészítésbe elég, ha csak a hiba oka kerül bele, nem kell cím, státusz, stb.

**Comment by KoToITKft** [comment]
Ezt legjobb tudomásom szerint nem mi befolyásoljuk, mi csak átvesszük.
Ezt egyeztetni fogom.

**Comment by suddenslap** [comment]
Át lett szervezve ennek a mezőnek az eddigi tartalma egy másik dedikált rendszer mezőbe. Tehát ha a Márkaműhely felől érkezik egy bejelentés, az eredeti bejelentés adatai nem a címkiegészítésbe kerülnek bele. Emiatt a munkalap pdf-en ezek az adatok nem szerepelnek többé, csak az az infó amit a felhasználó felvisz manuálisan a címkiegészítés mezőbe.
v1.0.0.6
