### ISSUE TITLE
 tervezett munka: új opciók

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#42]
cím lezárásnál, ha tervezett munkát csinálunk belőle, lehessen káreset, kábelhiba, gallyazás stb. opciókat választani

**Comment by suddenslap** [comment]
A tervezett munkánál van "Bejelentés oka" azt kéne feldúsítani ezekkel? Mi a teljes értékkészlet?

**Comment by KoToITKft** [comment]
Igen az kellene feldúsítani. Egyenlőre add hozzá a káreset, kábelhiba, gallyazás elemeket.
2 megoldást látok: 
1.: a keresés lehet open: vagyis az értékkészletből válasszon, mint alap, de ha a készlet helyett begépel valamit, akkor az legyen az a választás és esetleg kerüljön be az értékkészletbe
2.: vezessük ki ezeket a szótáradatokat egy törzs karbantartóba, ahol tetszőleges bővithető a lista

**Comment by suddenslap** [comment]
Hozzáadtam a 3 új értéket az értékkészlethez.
v1.0.0.6

A háttérben kódszótár van egyébként.
A kódszótár karbantartó felület jó megoldás lehet, viszont arra a kevés értékkészletre kicsit ágyúval verébre, mert pl ha módosítás van ugye csak lejáratni lehet kódokat, és úgy felvinni újakat (hogy a már hivatkozó rekordok ne őrüljenek meg), illetve van kb 4-5 kódcsoport néhány értékkel.
A másik megoldással az a baj, hogy az adatátstruktúrálást jelent, hiszen most egy fk van a táblában ezeken a helyeken és azt string-esíteni kéne, tehát én azt elvetném.

Ha nagyon kell nekik, egyszer meg lehet csinálni a kódszótár karbantartót, de addig lelkesen írunk egy insert-et, amivel megoldjuk a problémát.
