### ISSUE TITLE
Díszvilágítás: "F" és "K" gombok

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#5]
Díszvilágítás nodeban az F és K gombos szűrök nem müködnek. Kellene.

**Comment by suddenslap** [comment]
Működik a két gomb a Díszvilágítások gyűjtő esetén is. Erről kéne valami teszt videó, mert nem tudom reprodukálni.

**Comment by KoToITKft** [comment]
A kért film. Igazad van tényleg müködik. A video csak egy apróságot mutat.
[bandicam 2020-01-26 23-27-33-410.zip](https://github.com/koto-it-kft/NKVIL/files/4114668/bandicam.2020-01-26.23-27-33-410.zip)

**Comment by suddenslap** [comment]
Ha az a hiba, hogy a frissítés után másik sorra ugrik a TreeView-ben a kijelölés, akkor az sajnos ilyen. Az aktuális sort indexet jegyzi meg a komponens. Még azt tudom csinálni, hogy kiveszem a kijelölést, tehát hogy frissítés után újra ki kelljen jelölni az adott sort, de akkor meg ki fognak végezni minket...
A szűrős probléma elhárult, mert a #6 miatt kellett itt javítani.
