### ISSUE TITLE
Díszvilágítás: területi bontás

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#6]
Díszvilágításon belül is kellene a területi szétválasztás, mint a bejelentéseknél.

**Comment by suddenslap** [comment]
Kivittem a "fő" szintre a TreeView-ban "Díszvilágítás bejelentések" névvel a díszvilágítást. Ezalatt van rendes területi bontás. Az a baj, hogy  a "sima" bejelentésekbe nem számoljuk bele a díszvilágításos bejelentéseket, csak akkor, ha egyébként arra a user jogosult, tehát a területei között szerepel az éppen aktuális díszvilágításos terület. Viszont ezt így dinamikusan kezelni bonyás, úgyhogy az egyszerűbb utat próbáljuk meg először. Szóval ha valaki jogosult a díszvilágítást látni, és ha van 100 bejelentése, és 0 díszvilágítás bejelentése, és a 100ból 1-et díszvilágításossá tesz, akkor a sima bejelentéseknél 99 lesz míg a díszvilágításos bejelentéseknél 1. Ha a díszvilágítás területet nem látja, akkor is 99 lesz a sima bejelentéseknél, mert ugye a szabály az ez, hogy ezt ilyenkor nem láthatja. Remélhetőleg elfogadják így.

**Comment by KoToITKft** [comment]
én megvettem
