### ISSUE TITLE
Munkautasítás: lezárásnál 4:3 monitoron

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#7]
![image](https://user-images.githubusercontent.com/49682022/72251593-67f07a80-35fe-11ea-8a21-e0199acabd57.png)

Régi 4:9-as arányú monitoron nem látszik a lezárásnál az ablak vége. Ennél fogva nem lehet a Tervezett munka gombot elérni. Az ablak nem méretezhető,  nem lehet kimaximálni. Az oszlopok mérete is fix. Valahogy ezt változtani kellene.

**Comment by suddenslap** [comment]
250px-re korlátozva a "Bejelentés címe" oszlop szélessége, a munkautasítás Bejelentés részletezőjében.
