### ISSUE TITLE
Bejelentések: cimelemzés

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#8]
Ahogy nézem a MIRTSZ címeket úgy tűnik, hogy a MIRTUSZ csak a kerületig követeli meg a cimzést. Amennyiben nincs utca és házszám adat azt át sem küldi, nincs ilyen mező az adatban.
Lehet, hogy nekünk azt ez követni kellene. Tehát nem utca->kerület hanem kerület -> utca irányt kellene használni a terület meghatározásánál. Csak hogy minnél kevesebb legyen az N/A.

**Comment by suddenslap** [comment]
A cím törzsadat a KVIL rendszerben: utca -> település (irszám) -> terület (város). Tehát ennek a 3db adatnak rendelkezésre kell állnia, ahhoz hogy cím legyen belőle. Ha nincs utca a forrásrendszerben, azt nem tudjuk átvenni, hiszen nincs mit kitalálni helyette. Az, hogy Budapest 2. kerület, nem cím. A cím törzsadat azért a szűkebb irányból indul (utca), mert így egyetlen referenciával meg lehet kapni a teljes címet. Ha azt akarnánk, hogy legyenek cím "részeredmények", tehát pl Budapest 2. kerület, akkor a cím minden egyes részét külön-külön kéne hozzárendelnem a bejelentésekhez.
Nem lehetetlen megcsinálni, de mindent át kell struktúrálni hozzá a programban, úgyhogy az egy nagyobb volumenű fejlesztés.

**Comment by KoToITKft** [comment]
meg a nagy pacipéniszt, marad igy
