### ISSUE TITLE
Munkautasítás státuszolás

### ISSUE THREAD

**Issue by KoToITKft** [koto-it-kft/NKVIL#9]
Be kell vezetni a munkautasítás státuszát:
Kiadva (amikor létrejött, vagy módosítják)
és
Lezárva, ha minden rajta lévő bejelentés lezárt lesz (vagy mert elvégezték, vagy mert átkerült másik munkautasításra)
A munkautasítás listában pedig erre a két státuszra jelenhetnek meg adatok.

**Comment by suddenslap** [comment]
javítva 1.0.0.3
